# Лабораторная работа №2

ФИО:  **указать**   
Группа: **указать**  

Отправлять можно следующими способами (**обязательно указать свое ФИО и группу в каком-либо виде**):
1. Создать **приватный** репозиторий на github, добавить меня по нику (l3lush) в Collaborators (Settings -> Collaborators -> Add people)
2. Отправить заполненный ноутбук мне на почту avmysh@gmail.com, либо m1603956@edu.misis.ru
3. Отправить заполненный ноутбук мне в тг @l3lush. 

**Deadlines**:
- soft -- **02.04.2023 23:59** (за сдачу в пределах этого времени +1 балл в табличку)
- hard -- **16.04.2023 23:59**


**Что необходимо сделать**:
1. Заполнить все ячейки ниже кодом так, чтобы прошли все `assert`ы.

# Задача 1. Реализовать слой с функцией активации "сигмоида"

![](https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Logistic-curve.svg/1200px-Logistic-curve.svg.png)

Формула сигмоиды:
$$
f(x) = \frac {1}{1 + e^{-x}}
$$

In [1]:
import numpy as np

In [35]:
class SigmoidLayer():
    def __init__(self):
        self.params = []
        self.gradInput = None
        pass

    def forward(self, X):
        self.X = X.copy()
        output = 1 / (1 + np.exp(-X))
        return output
        pass

In [36]:
np.random.seed(17)

X = np.random.random(size=(100, 3))
sigmoid = SigmoidLayer()
output = sigmoid.forward(X)
correct_answer = np.array([[0.57313782, 0.62961995, 0.54773438],
                           [0.51696857, 0.68718368, 0.65843628],
                           [0.65419284, 0.64005501, 0.50976449],
                           [0.58851107, 0.7202462 , 0.51500666],
                           [0.70350447, 0.70626044, 0.51279562]])
assert np.isclose(output[:5], correct_answer).all()
assert hasattr(sigmoid, "params"), "Нет параметра params в реализованном классе"
assert hasattr(sigmoid, "gradInput"), "Нет параметра gradInput в реализованном классе"
assert hasattr(sigmoid, "X"), "Не сохранили X в реализованном классе"

# Задача 2. Реализовать слой с активацией гиперболического тангенса

![](https://production-media.paperswithcode.com/methods/Screen_Shot_2020-05-27_at_4.23.22_PM_dcuMBJl.png)

In [37]:
class TanhLayer():
    def __init__(self):
        self.params = []
        self.gradInput = None
        pass

    def forward(self, X):
        self.X = X.copy()
        output = (np.exp(X) - np.exp(-X)) / (np.exp(X) + np.exp(-X))
        return output
        pass

In [38]:
np.random.seed(17)

X = np.random.random(size=(100, 3))
tanh = TanhLayer()
output = tanh.forward(X)
correct_answer = np.array([[0.28642281, 0.48582948, 0.18921297],
                           [0.0677962 , 0.65669792, 0.57591821],
                           [0.5632092 , 0.51946218, 0.03904306],
                           [0.34328675, 0.73782249, 0.05997262],
                           [0.69833441, 0.70505935, 0.05114899]])
assert np.isclose(output[:5], correct_answer).all()
assert hasattr(tanh, "params"), "Нет параметра params в реализованном классе"
assert hasattr(tanh, "gradInput"), "Нет параметра gradInput в реализованном классе"
assert hasattr(tanh, "X"), "Не сохранили X в реализованном классе"

# Задача 3. Реализовать функцию потерь MSE

В качестве интерактива-микрозадания, поищите формулу MSE в гугле 😊

In [18]:
class MSELoss():
    def forward(self, y_true, y_pred):
        n = len(y_true)
        loss = (1 / n) * np.sum((y_true - y_pred) ** 2)
        return loss
        pass

In [19]:
np.random.seed(17)

y_true = np.random.randint(0, 1000, size=(100))
y_pred = np.random.randint(0, 1000, size=(100))
mse = MSELoss()
output = mse.forward(y_true, y_pred)
correct_answer = 157953.51
assert round(output) == round(correct_answer)

# Задача 4. Реализовать каркас нейросети

In [20]:
class LinearLayer:
    """
    Линейный слой с семинаров, ничего менять не надо
    """
    def __init__(self, in_size, out_size):
        self.W = np.random.randn(in_size, out_size)
        self.params = [self.W]
        self.gradW = None
        self.gradInput = None
        
    def forward(self, X):
        self.X = X.copy()
        output = X.dot(self.W)
        return output


class NN:
    def __init__(self, loss_func):
        self.layers = []
        self.params = []
        self.grads = []
        self.loss_func = loss_func
        pass

    def add_layer(self, layer):
        self.layers.append(layer)
        pass

    def forward(self, X):
        for layer in self.layers:
            X = layer.forward(X)
            print(X) 
        return X
        pass

In [21]:
nn = NN(MSELoss())

assert hasattr(nn, "layers")
assert hasattr(nn, "params")
assert hasattr(nn, "grads")
assert hasattr(nn, "loss_func")
assert isinstance(nn.loss_func, MSELoss)

In [39]:
np.random.seed(17)

X = np.random.random(size=(100, 3))
nn = NN(MSELoss())

linear1 = LinearLayer(3, 5)
nn.add_layer(linear1)

sigmoid1 = SigmoidLayer()
nn.add_layer(sigmoid1)

linear2 = LinearLayer(5, 1)
nn.add_layer(linear2)

sigmoid2 = SigmoidLayer()
nn.add_layer(sigmoid2)

output_nn = nn.forward(X)

assert round(output_nn.sum()) == 65

[[-7.34214336e-02  2.19697695e-01  9.21561730e-01 -1.11175540e-02
  -8.94952944e-01]
 [-2.30342032e-01  3.77309638e-01  1.69801687e+00 -6.83171591e-01
  -3.69285684e-01]
 [ 2.61724922e-02  2.55024870e-01  9.99705323e-01  4.79290273e-01
  -1.73875690e+00]
 [-1.89655868e-01  2.34106493e-01  9.47562736e-01 -7.69717975e-02
  -1.33000137e+00]
 [ 3.51783492e-03  3.56744223e-01  1.40077543e+00  5.99788452e-01
  -2.41472330e+00]
 [ 4.36690767e-02  4.80402957e-01  2.05103606e+00  2.06341609e-01
  -1.54757312e+00]
 [ 7.25564955e-02  2.82451114e-01  1.18393734e+00  2.97732375e-01
  -1.12702250e+00]
 [ 6.57692971e-02  5.14123742e-01  2.24067703e+00  6.92979513e-02
  -1.18204134e+00]
 [ 9.51159494e-02  1.89293544e-01  7.73114239e-01  3.68592031e-01
  -9.55802085e-01]
 [-2.14966941e-01  2.19349805e-01  9.67053301e-01 -4.64825010e-01
  -4.37369788e-01]
 [-2.01514727e-01  3.81989900e-01  1.68499580e+00 -4.93762256e-01
  -7.18813307e-01]
 [-1.50052319e-01  1.51955068e-01  6.56144603e-01 -2.67757579e-01

# Задача 5. Соберите свою собственную нейросеть

Конфигурация сети, как на картинке
![](https://waksoft.susu.ru/wp-content/uploads/2021/05/nn-title.png)
Активации любые на ваш вкус (можете чередовать, делать одни и те же и прочее, что душе угодно)

In [40]:
np.random.seed(17)

nn = NN(MSELoss())

linear1 = LinearLayer(4, 4)
nn.add_layer(linear1)

linear1 = LinearLayer(4, 5)
nn.add_layer(linear1)

linear1 = LinearLayer(5, 6)
nn.add_layer(linear1)

linear1 = LinearLayer(6, 4)
nn.add_layer(linear1)

linear1 = LinearLayer(4, 3)
nn.add_layer(linear1)

linear1 = LinearLayer(3, 3)
nn.add_layer(linear1)

In [41]:
np.random.seed(17)
X = np.random.randn(100, 4)
output = nn.forward(X)

assert output.shape == (100, 3)

layer_weights = []
for layer in nn.layers:
    if isinstance(layer, LinearLayer):
        layer_weights.append(layer.W.shape)
right_weights = [(4, 4), (4, 5), (5, 6), (6, 4), (4, 3), (3, 3)]
assert layer_weights == right_weights

[[0.56863052 0.13533042 0.65110527 0.75865346]
 [0.73830754 0.86837183 0.47210442 0.41045099]
 [0.53710045 0.39226933 0.89763852 0.75993264]
 [0.13957644 0.46554237 0.63177511 0.14488665]
 [0.78832803 0.38380046 0.25119861 0.43781674]
 [0.27243678 0.73716186 0.62042059 0.39015836]
 [0.30866668 0.5327699  0.22924836 0.53991261]
 [0.31968429 0.58659236 0.72662018 0.46540903]
 [0.52594076 0.57458699 0.72476163 0.70466742]
 [0.63825148 0.61426654 0.23769234 0.1154752 ]
 [0.23950171 0.9659459  0.53163947 0.3331041 ]
 [0.63591428 0.52476637 0.65428452 0.66887709]
 [0.28575461 0.31302513 0.75383692 0.27221844]
 [0.56082723 0.35860828 0.60576953 0.68963255]
 [0.35204322 0.7659181  0.32941458 0.31407663]
 [0.44266013 0.53001265 0.31249732 0.04926026]
 [0.31097155 0.57066926 0.62774088 0.52087647]
 [0.93824265 0.64817068 0.30238971 0.49907599]
 [0.59702746 0.66474121 0.68464505 0.63552718]
 [0.36795966 0.82118802 0.77001309 0.51281651]
 [0.39493105 0.69167041 0.51431603 0.26111689]
 [0.71791608 

AssertionError: 

Если прошли все ассерты, поздравляю, теперь вы способны построить полносвязную сеть любой конфигурации для любой задачи 🥳️🥳️🥳️🥳️🥳️🥳️🥳️
![](https://kartinkof.club/uploads/posts/2022-06/1655926105_23-kartinkof-club-p-kartinki-s-nadpisyu-kto-molodets-ya-molode-24.jpg)